### ISSUE TITLE
Upgrade to react-redux@7

### ISSUE THREAD

**Issue by septs** [supasate/connected-react-router#317] opened 2019-06-04 09:41 UTC
```
npm WARN connected-react-router@6.4.0 requires a peer of react-redux@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

```
➜   npm info react-redux

react-redux@7.0.3 | MIT | deps: 6 | versions: 91
Official React bindings for Redux
https://github.com/reduxjs/react-redux

keywords: react, reactjs, redux

dist
.tarball: https://registry.npmjs.org/react-redux/-/react-redux-7.0.3.tgz
.shasum: 983c5a6de81cb1e696bd1c090ba826545f9170f1
.integrity: sha512-vYZA7ftOYlDk3NetitsI7fLjryt/widNl1SLXYvFenIpm7vjb4ryK0EeFrgn62usg5fYkyIAWNUPKnwWPevKLg==
.unpackedSize: 238.1 kB

dependencies:
@babel/runtime: ^7.4.3          invariant: ^2.2.4               prop-types: ^15.7.2
hoist-non-react-statics: ^3.3.0 loose-envify: ^1.4.0            react-is: ^16.8.6

maintainers:
- gaearon <dan.abramov@gmail.com>
- timdorr <timdorr@timdorr.com>

dist-tags:
latest: 7.0.3     next: 7.1.0-rc.1  previous: 4.4.10

published a month ago by acemarke <mark.erikson@gmail.com>
```

**Comment by andrew-farries** [comment] 2019-06-05 06:43
I think this is a duplicate of #287. There is a draft PR open (#303) to support `react-redux` v7.

**Closed** 2019-06-05 06:53 UTC
