### ISSUE TITLE
Connected-React-Router latest version is showing dependency issue

### ISSUE THREAD

**Issue by sachin-agarwal-by** [supasate/connected-react-router#482] opened 2021-02-22 15:19 UTC
I am using latest version of connected-react-routers and can see below error it was working for previous version 6.8.0

![image](https://user-images.githubusercontent.com/69183793/108728348-82aa5800-754f-11eb-9f9f-9f9194d619bd.png)

Latest version 6.9.0

**Comment by olezt** [comment] 2021-02-22 16:08
Duplicate of https://github.com/supasate/connected-react-router/issues/480

**Comment by supasate** [comment] 2021-02-22 17:08
Should be fixed in v6.9.1.

**Closed by supasate** 2021-02-22 17:08 UTC
