### ISSUE TITLE
ConnectedRouter is re-rendering when Redux store updates

### ISSUE THREAD

**Issue by jakewies** [supasate/connected-react-router#205] opened 2018-12-12 16:40 UTC
I recently migrated from the deprecated [`react-router-redux`](https://github.com/reactjs/react-router-redux) package to `connected-react-router` in order to successfully update `react-redux` to [`v6`](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0). The migration went well enough thanks to the detailed docs for this project. 

However, now that I am on `v6.0.0` of both `connected-react-router` and `react-redux` I am noticing some strange things occurring with the `ConnectedRouter` component.

## First issue

As [others](https://github.com/supasate/connected-react-router/issues/193) have already stated, the `ConnectedRouter` seems to be rendering two times on initial page load.

## Second issue

This is the larger one for me, and I'm still trying to figure out why it is happening. Basically, on any update to the state of my `redux` store, the `ConnectedRouter` component re-renders, causing unnecessary re-renders of any child components below it.

I set up an [example repo](https://github.com/jakewies/connected-react-router-poc) that you can clone to get more details. I'll give a brief description here:

### Description

I've setup my `redux` store according to the docs in this repository. Assuming this, here is a basic example using `ConnectedRouter`:

```jsx
// App.js

const App = () => (
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <div>
        <Nav />
        <Switch>
          <Route exact path="/" component={Home} />
          <Route path="/about" component={About} />
        </Switch>
      </div>
    </ConnectedRouter>
  </Provider>
)
```

The `Home` component renders a child `IncrementCount` component which dispatches an action to increment the count value stored in `redux` store:

```jsx
// IncrementCount.js

import { increment } from './actions'

const IncrementCount = ({ increment }) => (
  <button onClick={increment}>Increment</button>
)

export default connect(null, { increment })(IncrementCount)
```

The `About` component renders a child `CountValue` component which displays the current count:

```jsx
// CountValue.js

const CountValue = ({ value }) => (
  <div>{value}</div>
)

const mapStateToProps = ({ app }) => ({
  value: app.count
})

export default connect(mapStateToProps)(CountValue)
```

When incrementing the count on the `'/'` route, the `ConnectedRouter` re-renders along with the `Nav` component (doesn't even connect to the redux store), and the `Home` component.

This is not the expected behavior.

The expected behavior occurs when replacing `ConnectedRouter` with `BrowserRouter` from the `react-router-dom` library:

```jsx
// with BrowserRouter

const App = () => (
  <Provider store={store}>
    <BrowserRouter>
      <div>
        <Nav />
        <Switch>
          <Route exact path="/" component={Home} />
          <Route path="/about" component={About} />
        </Switch>
      </div>
    </ConnectedRouter>
  </Provider>
)
```

In the code above, incrementing the count value on the `'/'` route does not cause any unnecessary re-renders to the `Nav` or `Home` components.

**Comment by merildev** [comment] 2018-12-12 18:14
Same bug here, I tried different ways of rendering the component (prop, children prop, render prop) and it does not have any effect. The issue seems to be linked to `connected-react-router`.

**Comment by radziksh** [comment] 2018-12-12 19:20
@jakewies @merildev this workaround works for me: 
```
I found that changing any routes from using component prop to render prop did the trick:

Works

        <Switch>
          <Route path={'login'} render={props => <LoginContainer {...props} />} />
        </Switch>
Renders 2x

        <Switch>
          <Route path={'login'} component={props => <LoginContainer {...props} />} />
        </Switch>
```
https://github.com/supasate/connected-react-router/issues/193#issuecomment-446212265

**Comment by jakewies** [comment] 2018-12-12 19:36
@radziksh This has no affect on either of the problems this issue is trying to examine.

What versions of `react-redux` and `connected-react-router` are you using? The comment you posted is coming from [an issue](https://github.com/supasate/connected-react-router/issues/193#issuecomment-446212265) that references a different version of `connected-react-router`.

**Comment by Annatsu** [comment] 2018-12-14 07:44
@jakewies i cloned your repository to make some tests and try to fix the problem.

Looks like the problem was indeed inside the [ConnectedRouter](https://github.com/supasate/connected-react-router/blob/master/src/ConnectedRouter.js) component.

If you look at the file, in the function `createConnectedRouter`, it creates the `ConnectedRouter` extending React.Component.

Then, it creates a Container Component called `ConnectedRouterWithContext`, that connects it's children with the redux Context.

What happens is that `ConnectedRouterWithContext` is a functional component, and `ConnectedRouter` is just a React.Component class. They don't have `shouldComponentUpdate` implementations.
This is probably what's causing the re-renders. I've forked this repo, switched the `ConnectedRouter` to a `PureComponent`, and it seemed to work just like expected (like the `BrowserRouter` example).

**Comment by foffer** [comment] 2018-12-16 08:51
FWIW I'm getting an `Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.` error when calling setState in `componentDidMount` due to the multiple renders

**Comment by supasate** [comment] 2018-12-27 20:50
It should be fixed in [v6.1.0](https://github.com/supasate/connected-react-router/releases/tag/v6.1.0). Please let me know if it helps and feel free to re-open this issue if the problem still exists.

Thank you all for your contributions!

**Closed by supasate** 2018-12-27 20:50 UTC

**Comment by ArunaBalavijay** [comment] 2019-05-06 10:03
This issue seem to be exists still on 6.4.0. Any help please?

**Comment by yuanchieh-cheng** [comment] 2019-05-09 04:31
same issue here with 6.4.0.

**Comment by zammitjames** [comment] 2019-08-20 10:24
Same issue here on 6.4.0.

**Comment by myapos** [comment] 2019-09-02 12:23
Hello,

I am facing the same issue on 6.5.2. Is there any update on this? 

Thank you

**Comment by mayank-shekhar** [comment] 2019-09-30 12:07
Issue still present on 6.5.2

**Comment by dnyy** [comment] 2019-10-04 13:31
Yep, same here (also on 6.5.2)

**Comment by maxwell-git** [comment] 2019-11-01 01:55
Issue still present on 6.5.2

**Comment by RobCubed** [comment] 2020-04-29 21:23
Still seeing this on 6.8.0

**Comment by letnotimitateothers** [comment] 2020-05-06 11:40
Same issue for me too ..

**Comment by Miloshinjo** [comment] 2020-08-03 14:08
Still seeing rerenders on 6.8. 

Any workaround until an official fix comes around?

**Comment by pratishshr** [comment] 2020-12-14 09:16
same issue for me too..

**Comment by hcurnor** [comment] 2022-01-26 10:21
Still seeing this on 6.9.1

**Comment by NirmalanSindujan** [comment] 2022-03-11 08:00
the issue is still existing 6.9.2
